# Generated by Django 2.2.2 on 2019-06-05 11:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Мобильный номер')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('country', models.CharField(max_length=90, verbose_name='Страна')),
                ('city', models.CharField(max_length=189, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('image_1', models.ImageField(default='media/None/no-img.jpg', upload_to='media/', verbose_name='Фото')),
                ('image_2', models.ImageField(default='media/None/no-img.jpg', upload_to='media/', verbose_name='Фото')),
                ('image_3', models.ImageField(default='media/None/no-img.jpg', upload_to='media/', verbose_name='Фото')),
                ('image_4', models.ImageField(default='media/None/no-img.jpg', upload_to='media/', verbose_name='Фото')),
                ('image_5', models.ImageField(default='media/None/no-img.jpg', upload_to='media/', verbose_name='Фото')),
                ('image_6', models.ImageField(default='media/None/no-img.jpg', upload_to='media/', verbose_name='Фото')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('size', models.CharField(max_length=20, null=True, verbose_name='Размер')),
                ('quality', models.CharField(max_length=20, verbose_name='Состояние')),
                ('status', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopsite.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=20, verbose_name='Статус заказа')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopsite.Customer', verbose_name='Покупатель')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopsite.Goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
